{"name": "Получение ошибки данных о заказе без номера", "status": "passed", "description": "Проверка получения данных о заказе без номера | GET /api/v1/orders/track", "start": 1703754065696, "stop": 1703754066305, "uuid": "fd3ca88d-c83e-47f9-a44a-fc6af6352b89", "historyId": "e74b6de62489040d4bcd9e912354abc6", "testCaseId": "e74b6de62489040d4bcd9e912354abc6", "fullName": "tests.test_create_order.TestTrackingOrder#test_order_track_no_order_id_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestTrackingOrder"}, {"name": "host", "value": "Redmi6-Redmi6"}, {"name": "thread", "value": "5034-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}